apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoopenjdk-deployment
  namespace: apps
  labels:
    app: demoopenjdk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoopenjdk
  template:
    metadata:
      labels:
        app: demoopenjdk
    spec:
      containers:
        - name: demoopenjdk
          image: phx.ocir.io/oracledeveloper/k8s-perf-demo:openjdk.0.0.1-SNAPSHOT
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "2000m"
            limits:
              memory: "512Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8080
              name: native-port

---
apiVersion: v1
kind: Service
metadata:
  name: demoopenjdk-svc
  namespace: apps
  labels:
    app: demoopenjdk
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: LoadBalancer
  ports:
    - port : 8080
  selector:
    app: demoopenjdk

---
