apiVersion: apps/v1
kind: Deployment
metadata:
  name: demonativeopts-deployment
  namespace: apps
  labels:
    app: demonativeopts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demonativeopts
  template:
    metadata:
      labels:
        app: demonativeopts
    spec:
      containers:
        - name: demonativeopts
          image: phx.ocir.io/oracledeveloper/k8s-perf-demo:native-pgo.0.0.1-SNAPSHOT
          resources:
            requests:
              memory: "128Mi"
              cpu: "2000m"
            limits:
              memory: "256Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8080
              name: native-port

---
apiVersion: v1
kind: Service
metadata:
  name: demonativeopts-svc
  namespace: apps
  labels:
    app: demonativeopts
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: LoadBalancer
  ports:
    - port : 8080
  selector:
    app: demonativeopts

---
