---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "Prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.monitoring:9090",
                "version": 1
            }
        ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: monitoring
data:
  grafana.ini: |
    [server]
      protocol = http
      http_port = 3000
    [analytics]
      reporting_enabled = false
      check_for_updates = true
    [log]
      mode = console
      level = info
    [paths]
      data         = /var/lib/grafana/data
      logs         = /var/log/grafana
      plugins      = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning/dashboards
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-config
  namespace: monitoring
  labels:
    app: grafana
data:
  dashboard.yaml: |
    apiVersion: 1
    providers:
    - name: 'Graal Dashboards'
      orgId: 1
      folder: 'Benchmarks'
      type: file
      disableDeletion: false
      editable: true
      allowUiUpdates: true
      options:
        path: /etc/grafana/provisioning/dashboards/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-jibber
  namespace: monitoring
  labels:
    app: grafana
data:
  jibber.json: |-
    {
    "annotations": {
        "list": [
            {
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "target": {
                    "limit": 100,
                    "matchAny": false,
                    "tags": [],
                    "type": "dashboard"
                },
                "type": "dashboard"
            },
            {
                "datasource": "Prometheus",
                "enable": true,
                "expr": "",
                "iconColor": "red",
                "name": "New annotation",
                "target": {
                    "limit": 100,
                    "matchAny": false,
                    "tags": [],
                    "type": "dashboard"
                }
            }
        ]
    },
    "editable": true,
    "fiscalYearStartMonth": 0,
    "graphTooltip": 1,
    "id": 1,
    "links": [
        {
            "asDropdown": false,
            "icon": "external link",
            "includeVars": false,
            "keepTime": false,
            "tags": [],
            "targetBlank": false,
            "title": "Code Repo",
            "tooltip": "",
            "type": "link",
            "url": "https://github.com/krisfoster/ni-k8s-demo"
        }
    ],
    "liveNow": false,
    "panels": [
        {
            "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
            },
            "description": "Throughput (Requests / Sec) - Higher Better ⚡️👆",
            "fieldConfig": {
                "defaults": {
                    "color": {
                        "mode": "palette-classic"
                    },
                    "custom": {
                        "axisLabel": "",
                        "axisPlacement": "auto",
                        "barAlignment": 0,
                        "drawStyle": "line",
                        "fillOpacity": 0,
                        "gradientMode": "none",
                        "hideFrom": {
                            "legend": false,
                            "tooltip": false,
                            "viz": false
                        },
                        "lineInterpolation": "smooth",
                        "lineWidth": 1,
                        "pointSize": 5,
                        "scaleDistribution": {
                            "type": "linear"
                        },
                        "showPoints": "auto",
                        "spanNulls": false,
                        "stacking": {
                            "group": "A",
                            "mode": "none"
                        },
                        "thresholdsStyle": {
                            "mode": "line+area"
                        }
                    },
                    "mappings": [],
                    "thresholds": {
                        "mode": "absolute",
                        "steps": [
                            {
                                "color": "red",
                                "value": null
                            },
                            {
                                "color": "green",
                                "value": 600
                            }
                        ]
                    },
                    "unit": "reqps"
                },
                "overrides": []
            },
            "gridPos": {
                "h": 9,
                "w": 24,
                "x": 0,
                "y": 0
            },
            "id": 2,
            "options": {
                "legend": {
                    "calcs": [
                        "max"
                    ],
                    "displayMode": "table",
                    "placement": "bottom"
                },
                "tooltip": {
                    "mode": "multi",
                    "sort": "asc"
                }
            },
            "targets": [
                {
                    "datasource": {
                        "type": "prometheus",
                        "uid": "PBFA97CFB590B2093"
                    },
                    "exemplar": true,
                    "expr": "rate(http_server_requests_seconds_count{app=\"jibber-openjdk\", status=\"200\", uri=\"/jibber\"}[$__interval])",
                    "hide": false,
                    "interval": "",
                    "legendFormat": "OpenJDK",
                    "refId": "B"
                },
                {
                    "datasource": {
                        "type": "prometheus",
                        "uid": "PBFA97CFB590B2093"
                    },
                    "exemplar": true,
                    "expr": "rate(http_server_requests_seconds_count{app=\"jibber-native\", status=\"200\", uri=\"/jibber\"}[$__interval])",
                    "hide": false,
                    "interval": "",
                    "legendFormat": "GraalVM Native exe",
                    "refId": "A"
                }
            ],
            "title": "Throughput (Requests / Sec) - Higher Better ⚡️👆",
            "type": "timeseries"
        },
        {
            "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
            },
            "description": "Container Memory (RSS MB) - Lower Better ⚡️👇",
            "fieldConfig": {
                "defaults": {
                    "color": {
                        "mode": "palette-classic"
                    },
                    "custom": {
                        "axisLabel": "",
                        "axisPlacement": "auto",
                        "barAlignment": 0,
                        "drawStyle": "line",
                        "fillOpacity": 0,
                        "gradientMode": "none",
                        "hideFrom": {
                            "legend": false,
                            "tooltip": false,
                            "viz": false
                        },
                        "lineInterpolation": "linear",
                        "lineWidth": 1,
                        "pointSize": 5,
                        "scaleDistribution": {
                            "type": "linear"
                        },
                        "showPoints": "auto",
                        "spanNulls": false,
                        "stacking": {
                            "group": "A",
                            "mode": "none"
                        },
                        "thresholdsStyle": {
                            "mode": "off"
                        }
                    },
                    "mappings": [],
                    "thresholds": {
                        "mode": "absolute",
                        "steps": [
                            {
                                "color": "green",
                                "value": null
                            },
                            {
                                "color": "red",
                                "value": 80
                            }
                        ]
                    },
                    "unit": "decbytes"
                },
                "overrides": []
            },
            "gridPos": {
                "h": 8,
                "w": 24,
                "x": 0,
                "y": 9
            },
            "id": 4,
            "options": {
                "legend": {
                    "calcs": [
                        "max"
                    ],
                    "displayMode": "table",
                    "placement": "bottom"
                },
                "tooltip": {
                    "mode": "multi",
                    "sort": "none"
                }
            },
            "targets": [
                {
                    "datasource": {
                        "type": "prometheus",
                        "uid": "PBFA97CFB590B2093"
                    },
                    "exemplar": true,
                    "expr": "container_memory_rss{namespace=\"jibber\",image=~\".*:jibber.native.latest\"}",
                    "hide": false,
                    "interval": "",
                    "legendFormat": "GraalVM Native exe",
                    "refId": "B"
                },
                {
                    "datasource": {
                        "type": "prometheus",
                        "uid": "PBFA97CFB590B2093"
                    },
                    "exemplar": true,
                    "expr": "container_memory_rss{namespace=\"jibber\",image=~\".*:jibber.openjdk.latest\"}",
                    "interval": "",
                    "legendFormat": "OpenJDK",
                    "refId": "A"
                }
            ],
            "title": "Container Memory (RSS MB) - Lower Better ⚡️👇",
            "type": "timeseries"
        },
        {
            "datasource": {
                "type": "prometheus",
                "uid": "PBFA97CFB590B2093"
            },
            "description": "Container Start-up Time (s) - Lower Better ⚡️👇",
            "fieldConfig": {
                "defaults": {
                    "color": {
                        "mode": "thresholds"
                    },
                    "mappings": [],
                    "thresholds": {
                        "mode": "absolute",
                        "steps": [
                            {
                                "color": "green",
                                "value": null
                            },
                            {
                                "color": "red",
                                "value": 1
                            }
                        ]
                    },
                    "unit": "s"
                },
                "overrides": []
            },
            "gridPos": {
                "h": 6,
                "w": 12,
                "x": 0,
                "y": 17
            },
            "id": 6,
            "options": {
                "orientation": "auto",
                "reduceOptions": {
                    "calcs": [
                        "lastNotNull"
                    ],
                    "fields": "",
                    "values": false
                },
                "showThresholdLabels": false,
                "showThresholdMarkers": true
            },
            "pluginVersion": "8.4.4",
            "targets": [
                {
                    "datasource": {
                        "type": "prometheus",
                        "uid": "PBFA97CFB590B2093"
                    },
                    "exemplar": true,
                    "expr": "application_ready_time_seconds{app=\"jibber-native\"}",
                    "format": "time_series",
                    "interval": "",
                    "legendFormat": "GraalVM Native exe",
                    "refId": "A"
                },
                {
                    "datasource": {
                        "type": "prometheus",
                        "uid": "PBFA97CFB590B2093"
                    },
                    "exemplar": true,
                    "expr": "application_ready_time_seconds{app=\"jibber-openjdk\"}",
                    "format": "time_series",
                    "hide": false,
                    "interval": "",
                    "legendFormat": "OpenJDK",
                    "refId": "B"
                }
            ],
            "title": "Container Start-up Time (s) - Lower Better ⚡️👇",
            "type": "gauge"
        }
    ],
    "refresh": "5s",
    "schemaVersion": 35,
    "style": "dark",
    "tags": [],
    "templating": {
        "list": []
    },
    "time": {
        "from": "now-15m",
        "to": "now"
    },
    "timepicker": {
        "refresh_intervals": [
            "5s",
            "10s",
            "30s",
            "1m",
            "5m",
            "15m",
            "30m",
            "1h",
            "2h",
            "1d"
        ]
    },
    "timezone": "",
    "title": "Jibber API",
    "uid": "qA79viunk",
    "version": 1,
    "weekStart": ""
    }


