{
 "title": "Jibber API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput (Requests / Sec) - Higher Better ⚡️👆",
   "type": "timeseries",
   "description": "Throughput (Requests / Sec) - Higher Better ⚡️👆",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"jibber-openjdk\", status=\"200\", uri=\"/jibber\"}[$__interval])",
     "legendFormat": "OpenJDK"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"jibber-native\", status=\"200\", uri=\"/jibber\"}[$__interval])",
     "legendFormat": "GraalVM Native exe"
    }
   ]
  },
  {
   "title": "Container Memory (RSS MB) - Lower Better ⚡️👇",
   "type": "timeseries",
   "description": "Container Memory (RSS MB) - Lower Better ⚡️👇",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"jibber\",image=~\".*:jibber.native.latest\"}",
     "legendFormat": "GraalVM Native exe"
    },
    {
     "expr": "container_memory_rss{namespace=\"jibber\",image=~\".*:jibber.openjdk.latest\"}",
     "legendFormat": "OpenJDK"
    }
   ]
  },
  {
   "title": "Container Start-up Time (s) - Lower Better ⚡️👇",
   "type": "gauge",
   "description": "Container Start-up Time (s) - Lower Better ⚡️👇",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_ready_time_seconds{app=\"jibber-native\"}",
     "legendFormat": "GraalVM Native exe"
    },
    {
     "expr": "application_ready_time_seconds{app=\"jibber-openjdk\"}",
     "legendFormat": "OpenJDK"
    }
   ]
  }
 ]
}
{
 "title": "Transform API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput (Requests / Sec) - Higher Better ⚡️👆",
   "type": "timeseries",
   "description": "Throughput (Requests / Sec) - Higher Better ⚡️👆",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"transform-openjdk\", status=\"200\", uri=\"/transform\"}[$__interval])",
     "legendFormat": "OpenJDK"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"transform-native\", status=\"200\", uri=\"/transform\"}[$__interval])",
     "legendFormat": "GraalVM Native exe"
    }
   ]
  },
  {
   "title": "Container Memory (RSS MB) - Lower Better ⚡️👇",
   "type": "timeseries",
   "description": "Container Memory (RSS MB) - Lower Better ⚡️👇",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{namespace=\"transform\",image=~\".*:transform.native.latest\"}",
     "legendFormat": "GraalVM Native exe"
    },
    {
     "expr": "container_memory_rss{namespace=\"transform\",image=~\".*:transform.openjdk.latest\"}",
     "legendFormat": "OpenJDK"
    }
   ]
  },
  {
   "title": "Container Start-up Time (s) - Lower Better ⚡️👇",
   "type": "gauge",
   "description": "Container Start-up Time (s) - Lower Better ⚡️👇",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_ready_time_seconds{app=\"transform-native\"}",
     "legendFormat": "GraalVM Native exe"
    },
    {
     "expr": "application_ready_time_seconds{app=\"transform-openjdk\"}",
     "legendFormat": "OpenJDK"
    }
   ]
  }
 ]
}