{
 "title": "Demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{container=\"demoopenjdk\"}",
     "legendFormat": "OpenJDK"
    },
    {
     "expr": "container_memory_max_usage_bytes{container=\"demograalee\"}",
     "legendFormat": "GraalVM EE"
    },
    {
     "expr": "container_memory_max_usage_bytes{container=\"demonativeopts\"}",
     "legendFormat": "Native Image PGO"
    },
    {
     "expr": "container_memory_max_usage_bytes{container=\"demonative\"}",
     "legendFormat": "Native Image"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{container=\"demoopenjdk\"}",
     "legendFormat": "OpenJDK"
    },
    {
     "expr": "container_memory_max_usage_bytes{container=\"demograalee\"}",
     "legendFormat": "GraalVM EE"
    },
    {
     "expr": "container_memory_max_usage_bytes{container=\"demonative\"}",
     "legendFormat": "Native Image"
    },
    {
     "expr": "container_memory_max_usage_bytes{container=\"demonativeopts\"}",
     "legendFormat": "Native Image PGO"
    }
   ]
  },
  {
   "title": "Start-up",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds{app=\"demoopenjdk\"}",
     "legendFormat": "Open JDK"
    },
    {
     "expr": "application_started_time_seconds{app=\"demonativeopts\"}",
     "legendFormat": "Native Image"
    }
   ]
  },
  {
   "title": "GraalVM EEJVM Mem Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"demograalee\", area=\"heap\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "jvm_memory_used_bytes{app=\"demograalee\", area=\"nonheap\"}",
     "legendFormat": "Non-Heap"
    }
   ]
  },
  {
   "title": "Open JDK JVM Mem Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{app=\"demoopenjdk\", area=\"heap\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "jvm_memory_used_bytes{app=\"demoopenjdk\", area=\"nonheap\"}",
     "legendFormat": "Non-Heap"
    }
   ]
  },
  {
   "title": "Working Set",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"demonative\"}",
     "legendFormat": "Native"
    },
    {
     "expr": "container_memory_working_set_bytes{container=\"demoopenjdk\"}",
     "legendFormat": "OpenJDK"
    },
    {
     "expr": "container_memory_working_set_bytes{container=\"demograalee\"}",
     "legendFormat": "GraalVM EE"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{container=\"demonative\"}",
     "legendFormat": "Native"
    },
    {
     "expr": "container_memory_rss{container=\"demoopenjdk\"}",
     "legendFormat": "OpenJDK"
    },
    {
     "expr": "container_memory_rss{container=\"demograalee\"}",
     "legendFormat": "GraalVM EE"
    },
    {
     "expr": "container_memory_rss{container=\"demonativeopts\"}",
     "legendFormat": "Native PGO"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "description": "Requests / sec Primes API",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"demonative\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "Native"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"demoopenjdk\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "OpenJDK"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"demograalee\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "GraalVM EE"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"demonativeopts\", status=\"200\", uri=\"/primes\"}[$__interval])",
     "legendFormat": "Native Opt."
    }
   ]
  },
  {
   "title": "Requests / sec Jibber API",
   "type": "timeseries",
   "description": "Requests / sec",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"demonative\", status=\"200\", uri=\"/primes/jibber\"}[$__interval])",
     "legendFormat": "Native"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"demoopenjdk\", status=\"200\", uri=\"/primes/jibber\"}[$__interval])",
     "legendFormat": "OpenJDK"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"demograalee\", status=\"200\", uri=\"/primes/jibber\"}[$__interval])",
     "legendFormat": "GraalVM EE"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{app=\"demonativeopts\", status=\"200\", uri=\"/primes/jibber\"}[$__interval])",
     "legendFormat": "Native Opt."
    }
   ]
  }
 ]
}