apiVersion: apps/v1
kind: Deployment
metadata:
  name: jibber-native-deployment
  namespace: jibber
  labels:
    app: jibber-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jibber-native
  template:
    metadata:
      labels:
        app: jibber-native
    spec:
      containers:
        - name: jibber-native
          image: phx.ocir.io/oracledeveloper/k8s-perf-demo:jibber.native.0.0.2-SNAPSHOT
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "2000m"
            limits:
              memory: "256Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8080
              name: native-port

---
apiVersion: v1
kind: Service
metadata:
  name: jibber-native-svc
  namespace: jibber
  labels:
    app: jibber-native
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: LoadBalancer
  ports:
    - port : 8080
  selector:
    app: jibber-native

---
