apiVersion: apps/v1
kind: Deployment
metadata:
  name: jibber-native-deployment
  namespace: jibber
  labels:
    app: jibber-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jibber-native
  template:
    metadata:
      labels:
        app: jibber-native
    spec:
      containers:
        - name: jibber-native
          image: ${REPO_PATH}:jibber.native.latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "2000m"
            limits:
              memory: "256Mi"
              cpu: "2000m"
          ports:
            - containerPort: 8080
              name: native-port

---
apiVersion: v1
kind: Service
metadata:
  name: jibber-native-svc
  namespace: jibber
  labels:
    app: jibber-native
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: LoadBalancer
  ports:
    - port : 8080
  selector:
    app: jibber-native

---
